name: API ETL pipeline

on:
    push:
        branches:
            - main

jobs:
    read-from-api:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: install dependencies
              run: pip install -r requirements.txt

            - name: get data from api
              env:
                API_TOKEN: $ {{secrets.API_TOKEN}}
              run: python "secrets.py"

            


          